version: '2'
services:
  github:
    container_name: github
    image: github:latest
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=local
      - spring.datasource.url=jdbc:postgresql://postgres:5432/github?useUnicode=true&characterEncoding=UTF-8

    links:
      - postgres:postgres
    network_mode: bridge

  postgres:
    container_name: github-postgres
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github
    network_mode: bridge
